#!/usr/bin/env python3
"""
EdgeSenseNano: Wave-Motion Symbolic Synthesizer
Version: 0.9.4 (CHA Pool Optimized)
"""
import os
import sys
import re

# === КРИТИЧНО: Импортираме символната регресия ПРЕДИ torch, за да избегнем Segfault ===
# Добавяме ES в Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

try:
    # Първо зареждаме двигателите за символно откриване
    from src.symbolic_from_nn import symbolic_from_nn
    print("✅ Symbolic Discovery Engine loaded first (Safe Mode)")
except ImportError:
    print("❌ Грешка: Проверете пътя до src/symbolic_from_nn.py")
    sys.exit(1)

# Сега вече е безопасно да заредим останалите
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

# --- Настройки ---
n_rows = 100 # Увеличаваме редовете за по-добро откриване на синусоиди
n_features = 4
output_dir = "data"
os.makedirs(output_dir, exist_ok=True)
os.makedirs("outputs", exist_ok=True)

# --- 1️⃣ Функции за MISRA-C Експорт (Synergy Core) ---

def export_to_misra_c(equation_str, gravity_val=0.015, model_name="symbolic_model"):
    """
    Генерира MISRA-C:2012 съвместим C код с поддръжка на тригонометрия.
    """
    # Добавяме 'f' суфикс за float32_t константи
    misra_eq = re.sub(r'(?<![a-zA-Z])(\d+\.\d+)', r'\1f', equation_str)
    
    # Реално картографиране на функциите за C (math.h)
    misra_eq = misra_eq.replace("sin", "sinf").replace("cos", "cosf")
    misra_eq = misra_eq.replace("sqrt", "sqrtf").replace("exp", "expf")

    c_header = f"""/* * GENERATED BY EDGESENSE NANO v0.9.4
 * Synergy: Symbolic Wave-Motion Law + Gravitational Feedback
 */

#include <stdint.h>
#include <math.h>

typedef float float32_t;
#define GRAV_G {gravity_val}f

float32_t {model_name}_inference(float32_t x0, float32_t x1, float32_t x2) {{
    /* AZURO Discovery: Автоматично открит физичен закон */
    float32_t azuro_out = {misra_eq};

    /* Grav Synergy: Центростремителна стабилизация */
    float32_t synergy_force = -GRAV_G * azuro_out;
    
    return azuro_out + synergy_force;
}}
"""
    return c_header

# --- 2️⃣ Генериране на данни (Simulating Wave Interaction) ---
csv_path = os.path.join(output_dir, "sample.csv")
t = np.linspace(0, 10, n_rows)
# Симулираме реална физика: комбинация от шум и вълна
target_signal = 1.2 * np.sin(t) + 0.5 * np.cos(t * 0.5)

df = pd.DataFrame({
    "error":      target_signal + np.random.normal(0, 0.1, n_rows),
    "gyro_y":     np.random.randn(n_rows) * 2,
    "thrust":     np.random.randn(n_rows) * 0.5,
    "status":     np.random.randint(0, 2, size=n_rows)
})
df.to_csv(csv_path, index=False)
print(f"✅ Данни за вълново движение подготвени: {csv_path}")

# --- 3️⃣ SYMBOLIC REGRESSION (Тригонометричен режим) ---
print("\n🧠 Започва Symbolic Regression (Searching for Wave-Laws: sin, cos)...")

class DummyNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(n_features, 1)
    def forward(self, x):
        return self.fc(x)

model = type('obj', (object,), {'nn_model': DummyNN()})
X = df.iloc[:, :n_features].values.astype(np.float32)
feature_names = ["x0", "x1", "x2", "x3"]

# Включваме sin и cos в търсенето
# ЗАБЕЛЕЖКА: symbolic_from_nn трябва да приема тези аргументи
eq_str = symbolic_from_nn(model, X, feature_names, n_iterations=40)

print(f"\n📐 Получено символно уравнение:\n   {eq_str}")

# --- 4️⃣ Генериране на код ---
c_code = export_to_misra_c(eq_str)
c_file = os.path.join("outputs", "symbolic_model.c")

with open(c_file, "w", encoding="utf-8") as f:
    f.write(c_code)

print(f"💻 MISRA-C код генериран: {c_file}")
print("✅ Пайплайнът е готов за тестване в ЦХА.")