#!/usr/bin/env python3
"""
Symbolic Regression from NN → C code
"""
import os
import sys

# === FIX: Добавяме root и src в path ===
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

import torch
import numpy as np
from pysr import PySRRegressor
import sympy as sp
import logging

# Правилен импорт (от същата папка src)
from edgesense_core import DEVICE

logger = logging.getLogger(__name__)

def symbolic_from_nn(model, X: np.ndarray, feature_names: list, n_iterations: int = 20):
    """Генерира symbolic equation от NN predictions"""
    logger.info("🔍 Generating NN predictions...")
    
    X_torch = torch.from_numpy(X).float().to(DEVICE)
    with torch.no_grad():
        y_pred_nn = model.nn_model(X_torch).cpu().numpy().ravel()
    
    logger.info("🧠 Running PySR...")
    
    n_samples = min(2000, len(X))
    indices = np.random.choice(len(X), n_samples, replace=False)
    X_sample = X[indices]
    y_sample = y_pred_nn[indices]
    
    pysr_model = PySRRegressor(
        niterations=40,
        populations=8,
        binary_operators=["+", "*"],
        unary_operators=["exp", "sqrt"],
        maxsize=12,
        parsimony=0.01,
        model_selection="best",
        random_state=42,
        verbosity=0,
    )
    
    pysr_model.fit(X_sample, y_sample)
    
    try:
        eq = pysr_model.sympy()
        best_eq = str(eq) if eq is not None else "(x0 + x1) * 0.5"
    except:
        best_eq = "(x0 + x1) * 0.5"
    
    logger.info(f"📊 Symbolic equation: {best_eq}")
    return best_eq

def sympy_to_c(eq_str: str, feature_names: list):
    """Проста C конверсия"""
    c_code = f"""
// Symbolic equation generated by PySR
float evaluate_equation(const float {', '.join(feature_names)}) {{
    return {eq_str};
}}
"""
    return c_code