/* * GENERATED BY EDGESENSE NANO v0.9.4
 * Synergy: Symbolic Wave-Motion Law + Gravitational Feedback
 */

#include <stdint.h>
#include <math.h>

typedef float float32_t;

/* Гравитационен фактор за стабилност (Synergy) */
#define GRAV_G 0.015f 

/**
 * @brief Автоматично генериран AI контролер.
 * Уравнение: 0.4183573*x1 + sqrt(exp(sqrt(x0))) + 411.86838
 */
float32_t symbolic_model_inference(float32_t x0, float32_t x1, float32_t x2) {
    /* 1. Пресмятане на символното уравнение (AZURO Law) */
    /* x0 = error, x1 = gyro_y, x2 = thrust */
    float32_t azuro_out = (0.4183573f * x1) + sqrtf(expf(sqrtf(x0))) + 411.86838f;

    /* 2. Прилагане на Grav Synergy (Центростремителна стабилизация) */
    float32_t synergy_force = -GRAV_G * azuro_out;
    
    /* Крайна команда преди Safety Filter-а */
    return azuro_out + synergy_force;
}